apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: cluster-upgrade-index-before
  namespace: qa
spec:
  templates:
    - name: uninstall-milvus
      container:
        name: main
        image: 'bitnami/kubectl:1.21.4'
        command:
          - /bin/sh
          - '-c'
        args:
          - >-
            kubectl delete milvus {{workflow.parameters.milvus-release}} -n
            chaos-testing
        resources: {}
    - name: cluster-upgrade-index-before
      dag:
        tasks:
          - name: deploy-cluster
            arguments:
              parameters:
                - name: milvus-image-tag
                  value: '{{workflow.parameters.milvus-image-before}}'
            templateRef:
              name: deploy-memory-milvus-cluster
              template: deploy-memory-milvus-cluster
          - name: index-test-before
            arguments:
              parameters:
                - name: milvus-case
                  value: '{{workflow.parameters.case-before-upgrade}}'
            templateRef:
              name: upgrade-milvus-test
              template: milvus-test
            dependencies:
              - deploy-cluster
          - name: upgrade-milvus-image
            arguments:
              parameters:
                - name: milvus-image-tag
                  value: '{{workflow.parameters.milvus-image-after}}'
            templateRef:
              name: deploy-memory-milvus-cluster
              template: deploy-memory-milvus-cluster
            dependencies:
              - index-test-before
          - name: wait-pods-ready
            arguments:
              parameters:
                - name: milvus-release
                  value: '{{workflow.parameters.milvus-release}}'
            templateRef:
              name: wait-milvus-healthy
              template: wait-milvus-pods-ready
            dependencies:
              - upgrade-milvus-image
          - name: index-test-after
            arguments:
              parameters:
                - name: milvus-case
                  value: '{{workflow.parameters.case-after-upgrade}}'
            templateRef:
              name: upgrade-milvus-test
              template: milvus-test
            dependencies:
              - wait-pods-ready
          - name: e2e-test-check
            arguments:
              parameters:
                - name: milvus-release
                  value: '{{workflow.parameters.milvus-release}}'
                - name: milvus-repo
                  value: 'https://github.com/ThreadDao/milvus.git'
                - name: milvus-branch
                  value: master-chaos-argo
            templateRef:
              name: e2e-test-check
              template: e2e-test-check
            dependencies:
              - wait-pods-ready
  entrypoint: cluster-upgrade-index-before
  arguments:
    parameters:
      - name: milvus-image-repo
        value: harbor.milvus.io/dockerhub/milvusdb/milvus
      - name: milvus-image-tag
        value: 2.1.0-latest
      - name: milvus-image-before
        value: v2.1.1
      - name: milvus-image-after
        value: master-20220902-4c1e7bc
      - name: milvus-release
        value: cluster-upgrade
      - name: case-before-upgrade
        value: test_index_before_upgrade
      - name: case-after-upgrade
        value: test_check_index_before_upgrade
  serviceAccountName: qa-admin
  onExit: uninstall-milvus