apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  namespace: qa
  name: scale-out-in
spec:
  entrypoint: scale-out-in
  serviceAccountName: qa-admin
  arguments:
    parameters:
      - name: milvus-repo
        value: 'https://github.com/ThreadDao/milvus.git'
      - name: milvus-branch
        value: master-scale-101
      - name: scale-cases
        value: '[{"scale-case": "test_scale_query_node_replicas"} ]'
  templates:
    - name: scale-out-in
      steps:
        - - name: call-scale-test
            template: milvus-scale-test
            arguments:
              parameters:
                - name: scale-case
                  value: '{{item.scale-case}}'
            withParam: '{{workflow.parameters.scale-cases}}'
    - name: milvus-scale-test
      inputs:
        parameters:
          - name: scale-case
      steps:
        - - name: scale-test
            template: scale-test
            arguments:
              parameters:
                - name: scale-case
                  value: '{{inputs.parameters.scale-case}}'
    - name: scale-test
      inputs:
        parameters:
          - name: scale-case
        artifacts:
          - name: source
            path: /src/milvus
            git:
              repo: '{{workflow.parameters.milvus-repo}}'
              revision: '{{workflow.parameters.milvus-branch}}'
              insecureIgnoreHostKey: true
      container:
        name: 'main'
        image: 'harbor.milvus.io/qa/fouram:1.1'
        command:
          - /bin/bash
          - '-c'
        args:
          - >-
            cd /src/milvus/tests/python_client && pip install --upgrade
            setuptools && pip install --upgrade pip &&  pip install
            --no-cache-dir -r requirements.txt && export IN_CLUSTER=true && cd scale/ && pytest . -k "{{inputs.parameters.scale-case}}" -v -s
