apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: deploy-memory-milvus-cluster
  namespace: qa
spec:
  entrypoint: deploy-memory-milvus-cluster
  templates:
    - name: deploy-memory-milvus-cluster
      inputs:
        parameters:
          - name: datanode-replicas
            value: '1'
          - name: datanode-memory-limit
            value: 6Gi
          - name: datanode-cpu-limit
            value: '2'
          - name: indexnode-replicas
            value: '1'
          - name: indexnode-memory-limit
            value: 6Gi
          - name: indexnode-cpu-limit
            value: '2'
          - name: querynode-replicas
            value: '1'
          - name: querynode-memory-limit
            value: 6Gi
          - name: querynode-cpu-limit
            value: '2'
      steps:
        - - name: deploy-milvus-cluster
            template: deploy-milvus
            arguments:
              parameters:
                - name: datanode-replicas
                  value: '{{inputs.parameters.datanode-replicas}}'
                - name: datanode-memory-limit
                  value: '{{inputs.parameters.datanode-memory-limit}}'
                - name: datanode-cpu-limit
                  value: '{{inputs.parameters.datanode-cpu-limit}}'
                - name: indexnode-replicas
                  value: '{{inputs.parameters.indexnode-replicas}}'
                - name: indexnode-memory-limit
                  value: '{{inputs.parameters.indexnode-memory-limit}}'
                - name: indexnode-cpu-limit
                  value: '{{inputs.parameters.indexnode-cpu-limit}}'
                - name: querynode-replicas
                  value: '{{inputs.parameters.querynode-replicas}}'
                - name: querynode-cpu-limit
                  value: '{{inputs.parameters.querynode-cpu-limit}}'
                - name: querynode-memory-limit
                  value: '{{inputs.parameters.querynode-memory-limit}}'
        - - name: wait-healthy
            templateRef:
              name: wait-milvus-healthy
              template: wait-milvus-healthy
            arguments:
              parameters:
                - name: milvus-release
                  value: '{{workflow.parameters.milvus-release}}'
    - name: deploy-milvus
      inputs:
        parameters:
          - name: datanode-replicas
          - name: datanode-memory-limit
          - name: datanode-cpu-limit
          - name: indexnode-replicas
          - name: indexnode-memory-limit
          - name: indexnode-cpu-limit
          - name: querynode-replicas
          - name: querynode-cpu-limit
          - name: querynode-memory-limit
      resource:
        action: apply
        manifest: |
          apiVersion: milvus.io/v1beta1
          kind: Milvus
          metadata:
            name: {{workflow.parameters.milvus-release}}
            namespace: chaos-testing
          spec:
            mode: cluster
            dependencies:
              etcd:
                inCluster:
                  deletionPolicy: Delete
                  pvcDeletion: true
              pulsar:
                inCluster:
                  deletionPolicy: Delete
                  pvcDeletion: true
              storage:
                inCluster:
                  deletionPolicy: Delete
                  pvcDeletion: true
            components:
              image: {{workflow.parameters.milvus-image-repo}}:{{workflow.parameters.milvus-image-tag}}
              imagePullPolicy: Always
              queryNode:
                replicas: {{inputs.parameters.querynode-replicas}}
                resources:
                  requests:
                    cpu: 100m
                    memory: 128Mi
                  limits:
                    cpu: {{inputs.parameters.querynode-cpu-limit}}
                    memory: {{inputs.parameters.querynode-memory-limit}}
              dataNode:
                replicas: {{inputs.parameters.datanode-replicas}}
                resources:
                  requests:
                    memory: 128Mi
                    cpu: 100m
                  limits:
                    cpu: {{inputs.parameters.datanode-cpu-limit}}
                    memory: {{inputs.parameters.datanode-memory-limit}}
              indexNode:
                replicas: {{inputs.parameters.indexnode-replicas}}
                resources:
                  requests:
                    memory: 128Mi
                    cpu: 100m
                  limits:
                    cpu: {{inputs.parameters.indexnode-cpu-limit}}
                    memory: {{inputs.parameters.indexnode-memory-limit}}
            config:
              log:
                level: debug
  arguments:
    parameters:
      - name: milvus-image-repo
        value: harbor.milvus.io/dockerhub/milvusdb/milvus-dev
      - name: milvus-image-tag
        value: 2.1.0-latest
      - name: milvus-release
        value: cluster-memory
  serviceAccountName: qa-admin
