apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: deploy-memory-milvus-standalone
  namespace: qa
spec:
  entrypoint: deploy-memory-milvus-standalone
  templates:
    - name: deploy-memory-milvus-standalone
      inputs:
        parameters:
          - name: standalone-memory-limit
            value: 6Gi
          - name: standalone-cpu-limit
            value: 2
      steps:
        - - name: deploy-milvus
            template: deploy-milvus
            arguments:
              parameters:
                - name: standalone-memory-limit
                  value: '{{inputs.parameters.standalone-memory-limit}}'
                - name: standalone-cpu-limit
                  value: '{{inputs.parameters.standalone-cpu-limit}}'
        - - name: wait-healthy
            templateRef:
              name: wait-milvus-healthy
              template: wait-milvus-healthy
            arguments:
              parameters:
                - name: milvus-release
                  value: '{{workflow.parameters.milvus-release}}'
    - name: deploy-milvus
      inputs:
        parameters:
          - name: standalone-memory-limit
          - name: standalone-cpu-limit
      resource:
        action: apply
        manifest: |
          apiVersion: milvus.io/v1beta1
          kind: Milvus
          metadata:
            name: {{workflow.parameters.milvus-release}}-
            namespace: chaos-testing
          spec:
            mode: standalone
            dependencies:
              etcd:
                inCluster:
                  deletionPolicy: Delete
                  pvcDeletion: true
              storage:
                inCluster:
                  deletionPolicy: Delete
                  pvcDeletion: true
              rocksmq:
                persistence:
                  enabled: true
            components:
              image: {{workflow.parameters.milvus-image-repo}}:{{workflow.parameters.milvus-image-tag}}
              imagePullPolicy: Always
              standalone:
                resources:
                  request:
                    cpu: 100m
                    memory: 128Mi
                  limits:
                    memory: {{inputs.parameters.standalone-memory-limit}}
                    cpu: {{inputs.parameters.standalone-cpu-limit}}
            config:
              log:
                level: debug
  arguments:
    parameters:
      - name: milvus-image-repo
        value: harbor.milvus.io/dockerhub/milvusdb/milvus-dev
      - name: milvus-image-tag
        value: 2.1.0-latest
      - name: milvus-release
        value: standalone-memory
  serviceAccountName: qa-admin
