apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: wait-milvus-healthy
  namespace: qa
spec:
  templates:
    - name: wait-milvus-healthy
      inputs:
        parameters:
          - name: milvus-release
      script:
        image: bitnami/kubectl:1.21.4
        command:
          - sh
        source: |
          kubectl -n qa wait --for=condition=MilvusReady milvus/{{inputs.parameters.milvus-release}} --timeout 30m
          kubectl describe milvus {{inputs.parameters.milvus-release}} -n qa
    - name: wait-milvus-pods-ready
      inputs:
        parameters:
          - name: milvus-release
      script:
        image: bitnami/kubectl:1.21.4
        command:
          - sh
        source: |
          kubectl wait --for=condition=ready pod -l app.kubernetes.io/instance={{inputs.parameters.milvus-release}} -n qa --timeout 20m
    - name: uninstall-both
      inputs:
        parameters:
          - name: milvus-release
      container:
        name: main
        image: bitnami/kubectl:1.21.4
        command:
          - /bin/sh
          - '-c'
#        todo delete which milvus release
        args:
          - >-
            kubectl delete milvus {{inputs.parameters.milvus-release}} {{workflow.parameters.standalone-release}} -n qa

