apiVersion: v1
kind: ConfigMap
metadata:
  name: scale-out-rg
  namespace: qa
data:
  config.yaml: |
    spec:
      components:
        queryNode:
          replicas: 4
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 1
              memory: 1Gi
        dataNode:
          replicas: 1
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              cpu: 1
              memory: 1Gi
        indexNode:
          replicas: 1
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              cpu: 1
              memory: 2Gi
      config:
        log:
          level: debug