apiVersion: v1
kind: ConfigMap
metadata:
  name: milvus-recall
  namespace: qa
data:
  config.yaml: |
    # This configuration is for the recall test

    # Connection parameters can be added dynamically
    connection_params:
      secure: false

    # Collection parameters can be added dynamically
    collection_params:
      collection_name: milvus_benchmark_collection
      other_fields: []

    insert_params:
    #  The data size of the vector inserted each time can be specified
      batch: 1000

    # Index parameters can be added dynamically
    index_params:
      index_type: HNSW
      index_param:
        M: 8
        efConstruction: 200

    # Load parameters can be added dynamically
    # example:
    #  load_params:
    #     timeout: 60
    load_params: {}

    # Search parameters can be added dynamically
    search_params:
      timeout: 1800

    # The following three sets of parameters will be cross-combined,
    # and then the corresponding recall rate test will be carried out in turn.
      top_k: [10]
      nq: [5000, 10000]
      search_param:
        ef: [16, 32]

    # After that, you can choose the most appropriate search parameters for concurrency testing
    # and get the optimal QPS of the server