apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: deploy-compact-mic
  namespace: argo
spec:
  templates:
    - name: deploy-compact-mic
      steps:
        - - name: deploy-compact-mic
            template: deploy-mic
        - - name: wait-healthy
            template: wait-healthy
    - name: deploy-mic
      resource:
        action: apply
        manifest: |
          apiVersion: milvus.io/v1alpha1
          kind: MilvusCluster
          metadata:
            name: '{{workflow.parameters.milvus-cluster-release}}'
            namespace: default
            labels:
              app: milvus
          spec:
            dependencies: 
              etcd:
                inCluster:
                  deletionPolicy: Delete
                  pvcDeletion: true
              pulsar:
                inCluster:
                  deletionPolicy: Delete
                  pvcDeletion: true
              storage:
                inCluster:
                  deletionPolicy: Delete
                  pvcDeletion: true
            components:
              image: harbor.zilliz.cc/milvus/milvus:{{workflow.parameters.milvus-image-tag}}
            config:
              log:
                level: debug
              common:
                retentionDuration: 40

    - name: wait-healthy
      script:
        image: bitnami/kubectl:1.21.4
        command: [sh]
        source: |
          kubectl -n default wait --for=condition=MilvusReady mic/{{workflow.parameters.milvus-cluster-release}} --timeout 20m
          kubectl describe milvus {{workflow.parameters.milvus-cluster-release}}
  entrypoint: deploy-compact-mic
  arguments:
    parameters:
      - name: milvus-image-tag
        value: master-latest
      - name: milvus-cluster-release
        value: mic-compact
  serviceAccountName: cluster-argo-milvus