apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: vdc-upgrade
  namespace: qa
spec:
  templates:
    - name: benchmark-loop
      steps:
        - - name: call-benchmark-test
            template: benchmark
            arguments:
              parameters:
                - name: server-instance
                  value: '{{workflow.name}}-{{item.instanceId}}'
                - name: server-configmap
                  value: '{{item.server-configmap}}'
                - name: upgrade-client-configmap
                  value: '{{workflow.parameters.upgrade-configmaps}}'
                - name: client-configmap
                  value: '{{item.client-configmap}}'
            withParam: '{{workflow.parameters.configmaps}}'
    - name: uninstall-all
      steps:
        - - name: uninstall-milvus
            template: uninstall-milvus
            arguments:
              parameters:
                - name: server-instance
                  value: '{{workflow.name}}-{{item.instanceId}}'
            withParam: '{{workflow.parameters.configmaps}}'
    - name: benchmark
      inputs:
        parameters:
          - name: server-instance
          - name: server-configmap
          - name: client-configmap
          - name: upgrade-client-configmap
      steps:
        - - name: install-milvus
            template: install-milvus
            arguments:
              parameters:
                - name: server-instance
                  value: '{{inputs.parameters.server-instance}}'
                - name: server-configmap
                  value: '{{inputs.parameters.server-configmap}}'
        - - name: client-test
            template: client-test
            arguments:
              parameters:
                - name: server-instance
                  value: '{{inputs.parameters.server-instance}}'
                - name: server-configmap
                  value: '{{inputs.parameters.server-configmap}}'
                - name: client-configmap
                  value: '{{inputs.parameters.client-configmap}}'
        - - name: upgrade-milvus
            template: upgrade-milvus
            arguments:
              parameters:
                - name: server-instance
                  value: '{{inputs.parameters.server-instance}}'
        - - name: re-client-test
            template: client-test
            arguments:
              parameters:
                - name: server-instance
                  value: '{{inputs.parameters.server-instance}}'
                - name: server-configmap
                  value: '{{inputs.parameters.server-configmap}}'
                - name: client-configmap
                  value: '{{inputs.parameters.upgrade-client-configmap}}'
    - name: uninstall-milvus
      inputs:
        parameters:
          - name: server-instance
        artifacts:
          - name: benchmark-src
            path: /src/benchmark
            git:
              repo: 'git@github.com:zilliztech/milvus_benchmark.git'
              revision: '{{workflow.parameters.test-client-branch}}'
              sshPrivateKeySecret:
                name: github-key
                key: ssh-private-key
              insecureIgnoreHostKey: true
      outputs: {}
      nodeSelector:
        node-role: test-client
      metadata: {}
      container:
        name: ''
        image: 'harbor-ap1.zilliz.cc/qa/fouram:1.1'
        command:
          - /bin/sh
          - '-c'
        args:
          - ' cd /src/benchmark/milvus_benchmark/vdc/ && export PYTHONPATH=/src/benchmark && python3.8 -W ignore vdc_deploy.py --instance-name={{inputs.parameters.server-instance}} --deploy-mode=delete --env=UAT '
        resources: {}
        volumeMounts:
          - name: kube-config
            readOnly: true
            mountPath: /root/.kube
          - name: db-data-path
            mountPath: /test
      volumes:
        - name: db-data-path
          persistentVolumeClaim:
            claimName: qa-pvc
      tolerations:
        - key: node-role
          operator: Equal
          value: vdc-test
          effect: NoSchedule
    - name: install-milvus
      inputs:
        parameters:
          - name: server-instance
          - name: server-configmap
        artifacts:
          - name: benchmark-src
            path: /src/benchmark
            git:
              repo: 'git@github.com:zilliztech/milvus_benchmark.git'
              revision: '{{workflow.parameters.test-client-branch}}'
              sshPrivateKeySecret:
                name: github-key
                key: ssh-private-key
              insecureIgnoreHostKey: true
      outputs: {}
      nodeSelector:
        node-role: test-client
      metadata: {}
      container:
        name: ''
        image: 'harbor-ap1.zilliz.cc/qa/fouram:1.1'
        command:
          - /bin/sh
          - '-c'
        args:
          - ' cd /src/benchmark/milvus_benchmark/vdc/ && cp /configmap-server/config.yaml . && export PYTHONPATH=/src/benchmark && python3.8 -W ignore vdc_deploy.py --instance-name={{inputs.parameters.server-instance}} --image-tag={{workflow.parameters.milvus-image-tag}} --deploy-params=config.yaml --deploy-mode=install --env=UAT '
        resources: {}
        volumeMounts:
          - name: kube-config
            readOnly: true
            mountPath: /root/.kube
          - name: benchmark-server-configmap
            mountPath: /configmap-server
          - name: db-data-path
            mountPath: /test
      volumes:
        - name: benchmark-server-configmap
          configMap:
            name: '{{inputs.parameters.server-configmap}}'
        - name: db-data-path
          persistentVolumeClaim:
            claimName: qa-pvc
      tolerations:
        - key: node-role
          operator: Equal
          value: vdc-test
          effect: NoSchedule
    - name: client-test
      inputs:
        parameters:
          - name: server-instance
          - name: server-configmap
          - name: client-configmap
        artifacts:
          - name: source
            path: /src
            git:
              repo: 'git@github.com:zilliztech/milvus_benchmark.git'
              revision: '{{workflow.parameters.test-client-branch}}'
              sshPrivateKeySecret:
                name: github-key
                key: ssh-private-key
              insecureIgnoreHostKey: true
      outputs: {}
      nodeSelector:
        node-role: test-client
      metadata: {}
      container:
        name: ''
        image: 'harbor-ap1.zilliz.cc/qa/fouram:1.1'
        command:
          - /bin/sh
          - '-c'
        args:
          - ' cd /src &&  python3.8 -m pip install -i https://pypi.doubanio.com/simple/  --trusted-host pypi.doubanio.com --upgrade pip && python3.8 -m pip install -r requirements_3.8.txt -i https://pypi.doubanio.com/simple/ --trusted-host pypi.doubanio.com &&  python3.8 -m pip install --extra-index-url https://test.pypi.org/simple/ pymilvus=={{workflow.parameters.test-sdk-version}} && cd milvus_benchmark && export PYTHONPATH=/src && python3.8 main.py --instance-name={{inputs.parameters.server-instance}} --local --suite=/configmap-client/config.yaml --server-config=/configmap-server/config.yaml'
        resources:
          limits:
            cpu: '1'
            memory: 8Gi
        volumeMounts:
          - name: kube-config
            readOnly: true
            mountPath: /root/.kube
          - name: benchmark-server-configmap
            mountPath: /configmap-server
          - name: benchmark-client-configmap
            mountPath: /configmap-client
          - name: db-data-path
            mountPath: /test
      volumes:
        - name: benchmark-server-configmap
          configMap:
            name: '{{inputs.parameters.server-configmap}}'
        - name: benchmark-client-configmap
          configMap:
            name: '{{inputs.parameters.client-configmap}}'
        - name: db-data-path
          persistentVolumeClaim:
            claimName: qa-pvc
      activeDeadlineSeconds: '{{workflow.parameters.activeDeadlineSeconds}}'
      tolerations:
        - key: node-role
          operator: Equal
          value: vdc-test
          effect: NoSchedule
    - name: upgrade-milvus
      inputs:
        parameters:
          - name: server-instance
        artifacts:
          - name: source
            path: /src/benchmark
            git:
              repo: 'git@github.com:zilliztech/milvus_benchmark.git'
              revision: '{{workflow.parameters.test-client-branch}}'
              insecureIgnoreHostKey: true
              sshPrivateKeySecret:
                name: github-key
                key: ssh-private-key
      nodeSelector:
        node-role: test-client
      tolerations:
        - key: node-role
          operator: Equal
          value: vdc-test
          effect: NoSchedule
      container:
        image: 'harbor-ap1.zilliz.cc/qa/fouram:1.1'
        command:
          - /bin/sh
          - '-c'
        args:
          - ' cd /src/benchmark/milvus_benchmark/vdc/ && export PYTHONPATH=/src/benchmark && python3.8 -W ignore vdc_deploy.py --instance-name={{inputs.parameters.server-instance}} --deploy-mode=upgrade --class-mode={{workflow.parameters.upgrade-class-mode}} --env=UAT'
        volumeMounts:
          - name: kube-config
            readOnly: true
            mountPath: /root/.kube
          - name: db-data-path
            mountPath: /test
      volumes:
        - name: db-data-path
          persistentVolumeClaim:
            claimName: qa-pvc
  entrypoint: benchmark-loop
  arguments:
    parameters:
      - name: activeDeadlineSeconds
        value: '1036800'
      - name: milvus-image-tag
        value: 936da41f
      - name: test-client-branch
        value: vdc
      - name: configmaps
        value: ' [ {"instanceId":"1", "server-configmap": "vdc-standalone-small", "client-configmap": "vdc-upgrade-client-locust-random" } ]'
      - name: upgrade-configmaps
        value: "vdc-upgrade-client-locust-random-concurrent"
      - name: upgrade-class-mode
        value: Middle
      - name: test-sdk-version
        value: 2.1.0.dev103
  volumes:
    - name: kube-config
      secret:
        secretName: qa-admin-config
  onExit: uninstall-all
