apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: vdc-ci-test
  namespace: qa
spec:
  templates:
    - name: vdc-ci-test
      steps:
        - - name: call-vdc-ci-test
            template: milvus-ci-test
            arguments:
              parameters:
                - name: server-instance
                  value: '{{workflow.name}}-{{item.instanceId}}'
                - name: server-configmap
                  value: '{{item.server-configmap}}'
            withParam: '{{workflow.parameters.configmaps}}'
    - name: uninstall-all
      steps:
        - - name: uninstall-milvus
            template: uninstall-milvus
            arguments:
              parameters:
                - name: server-instance
                  value: '{{workflow.name}}-{{item.instanceId}}'
            withParam: '{{workflow.parameters.configmaps}}'
    - name: milvus-ci-test
      inputs:
        parameters:
          - name: server-instance
          - name: server-configmap
      steps:
        - - name: install-milvus
            template: install-milvus
            arguments:
              parameters:
                - name: server-instance
                  value: '{{inputs.parameters.server-instance}}'
                - name: server-configmap
                  value: '{{inputs.parameters.server-configmap}}'
        - - name: ci-test
            template: ci-test
            arguments:
              artifacts:
                - name: endpoint
                  from: '{{steps.install-milvus.outputs.artifacts.endpoint}}'
    - name: install-milvus
      inputs:
        parameters:
          - name: server-instance
          - name: server-configmap
        artifacts:
          - name: benchmark-src
            path: /src/benchmark
            git:
              repo: 'git@github.com:zilliztech/milvus_benchmark.git'
              revision: '{{workflow.parameters.test-client-branch}}'
              sshPrivateKeySecret:
                name: github-key
                key: ssh-private-key
              insecureIgnoreHostKey: true
      outputs:
        artifacts:
          - name: endpoint
            path: /tmp/endpoint-pwd.txt
      nodeSelector:
        node-role: test-client
      container:
        name: ''
        image: 'harbor-ap1.zilliz.cc/qa/fouram:1.1'
        command:
          - /bin/sh
          - '-c'
        args:
          - ' cd /src/benchmark &&  python3.8 -m pip install -i https://pypi.doubanio.com/simple/  --trusted-host pypi.doubanio.com --upgrade pip && python3.8 -m pip install -r requirements_3.8.txt -i https://pypi.doubanio.com/simple/ --trusted-host pypi.doubanio.com && cd /src/benchmark/milvus_benchmark/vdc/ && cp /configmap-server/config.yaml . && export PYTHONPATH=/src/benchmark && python3.8 -W ignore vdc_deploy.py --instance-name={{inputs.parameters.server-instance}} --image-tag={{workflow.parameters.milvus-image-tag}} --deploy-params=config.yaml --deploy-mode=install --env=UAT && python3.8 -W ignore vdc_deploy.py --instance-name={{inputs.parameters.server-instance}} --deploy-mode=get_endpoint_pwd  --env=UAT'
        volumeMounts:
          - name: kube-config
            readOnly: true
            mountPath: /root/.kube
          - name: benchmark-server-configmap
            mountPath: /configmap-server
          - name: db-data-path
            mountPath: /test
      volumes:
        - name: benchmark-server-configmap
          configMap:
            name: '{{inputs.parameters.server-configmap}}'
        - name: db-data-path
          persistentVolumeClaim:
            claimName: qa-pvc
      tolerations:
        - key: node-role
          operator: Equal
          value: vdc-test
          effect: NoSchedule
    - name: ci-test
      inputs:
        artifacts:
          - name: endpoint
            path: /tmp/endpoint-pwd.txt
          - name: ci-source
            path: /src/milvus
            git:
              repo: 'https://github.com/milvus-io/milvus.git'
              revision: master
              insecureIgnoreHostKey: true
      container:
        name: ''
        image: 'harbor-ap1.zilliz.cc/qa/fouram:1.1'
        command:
          - /bin/sh
          - '-c'
        args:
          - ' host=$(cat /tmp/endpoint-pwd.txt| awk ''NR == 1 {print $1}'') && echo $host && port=$(cat /tmp/endpoint-pwd.txt | awk ''NR == 2 {print $1}'') && echo $port && pwd=$(cat /tmp/endpoint-pwd.txt | awk ''NR == 3 {print $1}'') && cd /src/milvus/tests/python_client && pip install --upgrade setuptools && pip install --upgrade pip &&  pip install --no-cache-dir -r requirements.txt && pwd && pytest . --tags L0 L1 -n 6 --host=$host --port=$port --user=root --password=$pwd'
        resources:
          limits:
            cpu: '6'
            memory: 12Gi
          requests:
            cpu: '1'
            memory: 5Gi
    - name: uninstall-milvus
      inputs:
        parameters:
          - name: server-instance
        artifacts:
          - name: benchmark-src
            path: /src/benchmark
            git:
              repo: 'git@github.com:zilliztech/milvus_benchmark.git'
              revision: '{{workflow.parameters.test-client-branch}}'
              sshPrivateKeySecret:
                name: github-key
                key: ssh-private-key
              insecureIgnoreHostKey: true
      nodeSelector:
        node-role: test-client
      container:
        name: ''
        image: 'harbor-ap1.zilliz.cc/qa/fouram:1.1'
        command:
          - /bin/sh
          - '-c'
        args:
          - ' cd /src/benchmark &&  python3.8 -m pip install -i https://pypi.doubanio.com/simple/  --trusted-host pypi.doubanio.com --upgrade pip && python3.8 -m pip install -r requirements_3.8.txt -i https://pypi.doubanio.com/simple/ --trusted-host pypi.doubanio.com && cd /src/benchmark/milvus_benchmark/vdc/ && export PYTHONPATH=/src/benchmark && python3.8 -W ignore vdc_deploy.py --instance-name={{inputs.parameters.server-instance}} --deploy-mode=delete --env=UAT '
        volumeMounts:
          - name: kube-config
            readOnly: true
            mountPath: /root/.kube
          - name: db-data-path
            mountPath: /test
      volumes:
        - name: db-data-path
          persistentVolumeClaim:
            claimName: qa-pvc
      tolerations:
        - key: node-role
          operator: Equal
          value: vdc-test
          effect: NoSchedule
  entrypoint: vdc-ci-test
  arguments:
    parameters:
      - name: activeDeadlineSeconds
        value: '1036800'
      - name: milvus-image-tag
        value: indexpool-17-7
      - name: test-client-branch
        value: vdc
      - name: configmaps
        value: '[{"instanceId":"1", "server-configmap": "vdc-standalone-small"} ]'
      - name: test-sdk-version
        value: 2.2.0.dev30
  volumes:
    - name: kube-config
      secret:
        secretName: qa-admin-config
  onExit: uninstall-all