apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: vdc-pool
  namespace: qa
spec:
  templates:
    - name: benchmark-loop
      steps:
        - - name: call-benchmark-test
            template: benchmark
            arguments:
              parameters:
                - name: server-instance
                  value: '{{workflow.name}}-{{item.instanceId}}'
                - name: server-configmap
                  value: '{{item.server-configmap}}'
                - name: client-configmap
                  value: '{{item.client-configmap}}'
            withParam: '{{workflow.parameters.configmaps}}'
    - name: benchmark
      inputs:
        parameters:
          - name: server-instance
          - name: server-configmap
          - name: client-configmap
      outputs: {}
      metadata: {}
      steps:
        - - name: client-test
            template: client-test
            arguments:
              parameters:
                - name: server-instance
                  value: '{{inputs.parameters.server-instance}}'
                - name: server-configmap
                  value: '{{inputs.parameters.server-configmap}}'
                - name: client-configmap
                  value: '{{inputs.parameters.client-configmap}}'
    - name: client-test
      inputs:
        parameters:
          - name: server-instance
          - name: server-configmap
          - name: client-configmap
        artifacts:
          - name: source
            path: /src
            git:
              repo: 'git@github.com:zilliztech/milvus_benchmark.git'
              revision: '{{workflow.parameters.test-client-branch}}'
              sshPrivateKeySecret:
                name: github-key
                key: ssh-private-key
              insecureIgnoreHostKey: true
      outputs: {}
      nodeSelector:
        node-role: test-client
      metadata:
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: 'false'
      container:
        name: ''
        image: 'harbor-us-vdc.zilliz.cc/qa/fouram:1.1'
        command:
          - /bin/sh
          - '-c'
        args:
          - ' cd /src &&  python3.8 -m pip install -i https://pypi.doubanio.com/simple/  --trusted-host pypi.doubanio.com --upgrade pip && python3.8 -m pip install -r requirements_3.8.txt -i https://pypi.doubanio.com/simple/ --trusted-host pypi.doubanio.com &&  python3.8 -m pip install --extra-index-url https://test.pypi.org/simple/ pymilvus=={{workflow.parameters.test-sdk-version}} && cd milvus_benchmark && export PYTHONPATH=/src && python3.8 main.py --instance-name={{inputs.parameters.server-instance}} --local --suite=/configmap-client/config.yaml --server-config=/configmap-server/config.yaml --region-id={{workflow.parameters.region-id}} --env=UAT3 '
        resources:
          limits:
            cpu: '1'
            memory: 8Gi
        volumeMounts:
          - name: kube-config
            readOnly: true
            mountPath: /root/.kube
          - name: benchmark-server-configmap
            mountPath: /configmap-server
          - name: benchmark-client-configmap
            mountPath: /configmap-client
          - name: db-data-path
            mountPath: /test
      volumes:
        - name: benchmark-server-configmap
          configMap:
            name: '{{inputs.parameters.server-configmap}}'
        - name: benchmark-client-configmap
          configMap:
            name: '{{inputs.parameters.client-configmap}}'
        - name: db-data-path
          persistentVolumeClaim:
            claimName: qa-pvc
      activeDeadlineSeconds: '{{workflow.parameters.activeDeadlineSeconds}}'
      tolerations:
        - key: node-role
          operator: Equal
          value: vdc-test
          effect: NoSchedule
  entrypoint: benchmark-loop
  arguments:
    parameters:
      - name: activeDeadlineSeconds
        value: '1036800'
      - name: kube-config-secret
        value: gcp-qa-admin-config
      - name: test-client-branch
        value: vdc
      - name: region-id
        value: gcp-us-west1
      - name: configmaps
        value: ' [ {"instanceId":"1", "server-configmap": "vdc-standalone-1cu", "client-configmap": "pool-index-sift6m-hnsw-96"} ]'
      - name: test-sdk-version
        value: 2.3.0.dev34
  volumes:
    - name: kube-config
      secret:
        secretName: '{{workflow.parameters.kube-config-secret}}'
