apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: test-standalone-memory-stress
  namespace: chaos-testing
spec:
  selector:
    namespaces:
      - default
    labelSelectors:
      app.kubernetes.io/name: milvus
      app.kubernetes.io/instance: standalone-memory
      app.kubernetes.io/component: standalone
  mode: all
  value: "2"
  stressors:
    memory:
      workers: 4
      size: 4Gi
  duration: 5m