apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: milvus-compaction-test
  namespace: qa
  labels:
    workflows.argoproj.io/test: compact
spec:
  templates:
    - name: compaction-test
      dag:
        tasks:
          - name: cluster-compaction-test
            template: cluster-compaction-test
          - name: standalone-compaction-test
            template: standalone-compaction-test
    - name: cluster-compaction-test
      steps:
        - - name: deploy-cluster
            templateRef:
              name: deploy-compact-milvus
              template: deploy-compact-cluster
        - - name: wait-healthy
            templateRef:
              name: wait-milvus-healthy
              template: wait-milvus-healthy
            arguments:
              parameters:
                - name: milvus-release
                  value: '{{workflow.parameters.cluster-release}}'
        - - name: client-test
            template: client-test
            arguments:
              parameters:
                - name: milvus-release
                  value: '{{workflow.parameters.cluster-release}}'
    - name: standalone-compaction-test
      steps:
        - - name: deploy-standalone
            templateRef:
              name: deploy-compact-milvus
              template: deploy-compact-standalone
        - - name: wait-healthy
            templateRef:
              name: wait-milvus-healthy
              template: wait-milvus-healthy
            arguments:
              parameters:
                - name: milvus-release
                  value: '{{workflow.parameters.standalone-release}}'
        - - name: client-test
            template: client-test
            arguments:
              parameters:
                - name: milvus-release
                  value: '{{workflow.parameters.standalone-release}}'
    - name: client-test
      inputs:
        parameters:
          - name: milvus-release
        artifacts:
          - name: source
            path: /src/milvus
            git:
              repo: '{{workflow.parameters.milvus-repo}}'
              revision: '{{workflow.parameters.milvus-revision}}'
              insecureIgnoreHostKey: true
      container:
        image: 'harbor.milvus.io/qa/fouram:1.0'
        command:
          - /bin/sh
          - '-c'
        args:
          - >-
            cd /src/milvus/tests/python_client && pip install --upgrade
            setuptools && pip install --upgrade pip &&  pip install -r requirements.txt
            && pytest testcases/test_compaction.py -n 4
            --host={{inputs.parameters.milvus-release}}-milvus.chaos-testing.svc.cluster.local
    - name: uninstall-both
      container:
        name: main
        image: 'harbor.milvus.io/qa/fouram:1.0'
        command:
          - /bin/sh
          - '-c'
        args:
          - >-
            kubectl delete milvus {{workflow.parameters.cluster-release}} {{workflow.parameters.standalone-release}} -n chaos-testing
  entrypoint: compaction-test
  arguments:
    parameters:
      - name: cluster-release
        value: compact-cluster
      - name: standalone-release
        value: compact-standalone
      - name: image-repo
        value: harbor.milvus.io/dockerhub/milvusdb/milvus
      - name: image-tag
        value: master-latest
      - name: milvus-repo
        value: https://github.com/milvus-io/milvus.git
      - name: milvus-revision
        value: master
  serviceAccountName: qa-admin
  onExit: uninstall-both
  activeDeadlineSeconds: 7200
  artifactGC:
    strategy: OnWorkflowDeletion