apiVersion: v1
kind: Pod
metadata:
  name: backup-mount
  namespace: chaos-testing
spec:
  volumes:
    - name: backup
      persistentVolumeClaim:
        claimName: release-upgrade
  containers:
    - name: main
      image: 'harbor.milvus.io/qa/fouram:1.0'
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      volumeMounts:
        - mountPath: "/milvus/data"
          name: backup