apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: milvus-compaction-test-cron
  namespace: qa
  labels:
    workflows.argoproj.io/test: compact
spec:
  workflowSpec:
    artifactGC:
      strategy: OnWorkflowDeletion
    podGC:
      strategy: OnWorkflowSuccess
    templates:
      - name: compaction-test-cron
        dag:
          tasks:
            - name: cluster-compaction-test
              templateRef:
                name: milvus-compaction-test
                template: cluster-compaction-test
            - name: standalone-compaction-test
              templateRef:
                name: milvus-compaction-test
                template: standalone-compaction-test
      - name: uninstall-all
        container:
          name: main
          image: 'harbor.milvus.io/qa/fouram:1.0'
          command:
            - /bin/sh
            - '-c'
          args:
            - >-
              kubectl delete milvus {{workflow.parameters.cluster-release}} {{workflow.parameters.standalone-release}} -n qa
    entrypoint: compaction-test-cron
    onExit: uninstall-all
    arguments:
      parameters:
        - name: cluster-release
          value: compact-cluster
        - name: standalone-release
          value: compact-standalone
        - name: image-repo
          value: harbor.milvus.io/dockerhub/milvusdb/milvus-dev
        - name: image-tag
          value: 2.1.0-latest
        - name: milvus-repo
          value: https://github.com/milvus-io/milvus.git
        - name: milvus-revision
          value: 2.1.0
    serviceAccountName: qa-admin
    activeDeadlineSeconds: 7200
  schedule: 0 22 * * *
  timezone: Asia/Shanghai