apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: standalone-memory-datanode-cron
  namespace: qa
  labels:
    workflows.argoproj.io/test: standalone-datanode
spec:
  schedule: 0 23 * * *
  timezone: Asia/Shanghai
  workflowSpec:
    entrypoint: standalone-memory-datanode-test
    onExit: uninstall-standalone
    serviceAccountName: qa-admin
    activeDeadlineSeconds: 7200
    arguments:
      parameters:
        - name: milvus-image-repo
          value: harbor.milvus.io/dockerhub/milvusdb/milvus-dev
        - name: milvus-image-tag
          value: 2.1.0-latest
        - name: milvus-release
          value: standalone-memory-datanode
        - name: collection-name
          value: standalone_data
    templates:
      - name: standalone-memory-datanode-test
        steps:
          - - name: standalone-memory-datanode
              templateRef:
                name: standalone-memory-datanode
                template: standalone-memory-datanode
      - name: uninstall-standalone
        container:
          name: main
          image: bitnami/kubectl:1.21.4
          command:
            - /bin/sh
            - '-c'
          args:
            - >-
              kubectl delete milvus {{workflow.parameters.milvus-release}} -n chaos-testing