apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: chaos-memory-stress-by-label
  namespace: chaos-testing
spec:
  entrypoint: chaos-memory-stress-by-label
  arguments:
    parameters:
      - name: milvus-release
        value: standalone-memory
  templates:
    - name: chaos-memory-stress-by-label
      inputs:
        parameters:
          - name: chaos-component
            value: standalone
          - name: chaos-duration
            value: 5m
          - name: memory-size
            value: 6Gi
          - name: chaos-mode
            value: all
      steps:
        - - name: chaos-memory-stress
            template: chaos-memory-stress
            arguments:
              parameters:
                - name: chaos-component
                  value: '{{inputs.parameters.chaos-component}}'
                - name: chaos-duration
                  value: '{{inputs.parameters.chaos-duration}}'
                - name: memory-size
                  value: '{{inputs.parameters.memory-size}}'
                - name: chaos-mode
                  value: '{{inputs.parameters.chaos-mode}}'
        - - name: suspend-duration
            template: suspend
            arguments:
              parameters:
                - name: duration
                  value: '{{steps.chaos-memory-stress.outputs.parameters.chaos-duration}}'
        - - name: delete-stress-chaos
            template: delete-stress-chaos
            arguments:
              parameters:
                - name: chaos-name
                  value: '{{steps.chaos-memory-stress.outputs.parameters.chaos-name}}'
    - name: chaos-memory-stress
      inputs:
        parameters:
          - name: chaos-component
            value: standalone
          - name: chaos-duration
            value: 5m
          - name: memory-size
            value: 6Gi
          - name: chaos-mode
            value: all
      resource:
        action: create
        manifest: |
          apiVersion: chaos-mesh.org/v1alpha1
          kind: StressChaos
          metadata:
            generateName: '{{inputs.parameters.chaos-component}}-memory-'
            namespace: chaos-testing
          spec:
            selector:
              namespaces:
                - default
              labelSelectors:
                app.kubernetes.io/name: milvus
                app.kubernetes.io/instance: {{workflow.parameters.milvus-release}}
                app.kubernetes.io/component: {{inputs.parameters.chaos-component}}
            mode: {{inputs.parameters.chaos-mode}}
            value: "2"
            stressors:
              memory:
                workers: 4
                size: {{inputs.parameters.memory-size}}
            duration: {{inputs.parameters.chaos-duration}}
      outputs:
        parameters:
          - name: chaos-name
            valueFrom:
              jsonPath: '{.metadata.name}'
          - name: chaos-duration
            valueFrom:
              jsonPath: '{.spec.duration}'
    - name: suspend
      inputs:
        parameters:
          - name: duration
      suspend:
        duration: '{{inputs.parameters.duration}}'
    - name: delete-stress-chaos
      inputs:
        parameters:
          - name: chaos-name
      script:
        image: bitnami/kubectl:1.21.4
        command: [ sh ]
        source: |
          echo {{inputs.parameters.chaos-name}}
          kubectl delete stresschaos {{inputs.parameters.chaos-name}} -n chaos-testing
  serviceAccountName: cluster-chaos-milvus