apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: chaos-milvus-test
  namespace: qa
spec:
  templates:
    - name: milvus-test
      inputs:
        parameters:
          - name: milvus-case
          - name: replica_num
            value: '1'
        artifacts:
          - name: source
            path: /src/milvus
            git:
              repo: 'https://github.com/ThreadDao/milvus.git'
              revision: chaos-argo
              insecureIgnoreHostKey: true
      outputs:
        artifacts:
          - name: client-logs
            path: /tmp/ci_logs
      container:
        name: ''
        image: 'harbor.milvus.io/qa/fouram:1.0'
        command:
          - /bin/sh
          - '-c'
        args:
          - >-
            cd /src/milvus/tests/python_client && pip install --upgrade
            setuptools && pip install --upgrade pip &&  pip install
            --no-cache-dir -r requirements.txt && pytest
            chaos/test_chaos_memory_argo.py::TestMilvusChaos::{{inputs.parameters.milvus-case}}
            --host={{workflow.parameters.milvus-release}}-milvus.qa.svc.cluster.local
            --collection_name={{workflow.parameters.collection-name}}
            --replica_num={{inputs.parameters.replica_num}} -v -s
      activeDeadlineSeconds: 3600
  arguments:
    parameters:
      - name: milvus-release
        value: standalone-memory
      - name: collection-name
        value: standalone_memory