apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: cluster-memory-querynode
  namespace: chaos-testing
spec:
  entrypoint: cluster-memory-querynode
  serviceAccountName: cluster-chaos-milvus
  arguments:
    parameters:
      - name: milvus-image-repo
        value: milvusdb/milvus-dev
      - name: milvus-image-tag
        value: 2.1.0-latest
      - name: milvus-release
        value: cluster-memory
      - name: collection-name
        value: cluster_query
  templates:
    - name: cluster-memory-querynode
      dag:
        tasks:
          - name: deploy-milvus
            templateRef:
              name: deploy-memory-milvus-cluster
              template: deploy-memory-milvus-cluster
            arguments:
              parameters:
                - name: querynode-memory-limit
                  value: 6Gi
          - name: init-collection
            dependencies:
              - deploy-milvus
            templateRef:
              name: chaos-milvus-test
              template: milvus-test
            arguments:
              parameters:
                - name: milvus-case
                  value: test_init_collection
          - name: load-collection
            dependencies:
              - init-collection
            templateRef:
              name: chaos-milvus-test
              template: milvus-test
            arguments:
              parameters:
                - name: milvus-case
                  value: test_load_failed
          - name: apply-memory-chaos
            dependencies:
              - init-collection
            templateRef:
              name: chaos-memory-stress-by-label
              template: chaos-memory-stress-by-label
            arguments:
              parameters:
                - name: memory-size
                  value: 6Gi
                - name: chaos-component
                  value: querynode
          - name: wait-pods-ready
            dependencies:
              - load-collection
              - apply-memory-chaos
            templateRef:
              name: wait-milvus-healthy
              template: wait-milvus-pods-ready
              clusterScope: true
            arguments:
              parameters:
                - name: milvus-release
                  value: '{{workflow.parameters.milvus-release}}'
          - name: init-collection-check
            dependencies:
              - wait-pods-ready
            templateRef:
              name: chaos-milvus-test
              template: milvus-test
            arguments:
              parameters:
                - name: milvus-case
                  value: test_init_collection_check
          - name: e2e-test-check
            dependencies:
              - wait-pods-ready
            templateRef:
              name: e2e-test-check
              template: e2e-test-check
              clusterScope: true
            arguments:
              parameters:
                - name: milvus-release
                  value: '{{workflow.parameters.milvus-release}}'
                - name: milvus-repo
                  value: 'https://github.com/ThreadDao/milvus.git'
                - name: milvus-branch
                  value: memory-replica