apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: deploy-memory-milvus-cluster
  namespace: chaos-testing
spec:
  entrypoint: deploy-memory-milvus-cluster
  templates:
    - name: deploy-memory-milvus-cluster
      steps:
        - - name: deploy-milvus-cluster
            template: deploy-milvus
        - - name: wait-healthy
            templateRef:
              name: wait-milvus-healthy
              template: wait-milvus-healthy
              clusterScope: true
            arguments:
              parameters:
                - name: milvus-release
                  value: '{{workflow.parameters.milvus-release}}'
    - name: deploy-milvus
      inputs:
        parameters:
          - name: datanode-replicas
            value: '1'
          - name: datanode-memory-limit
            value: 6Gi
          - name: indexnode-replicas
            value: '1'
          - name: indexnode-memory-limit
            value: 6Gi
          - name: querynode-replicas
            value: '1'
          - name: querynode-memory-limit
            value: 6Gi
      resource:
        action: apply
        manifest: |
          apiVersion: milvus.io/v1beta1
          kind: Milvus
          metadata:
            name: {{workflow.parameters.milvus-release}}
            namespace: default
            labels:
              app: milvus
          spec:
            mode: cluster
            dependencies:
              etcd:
                inCluster:
                  deletionPolicy: Delete
                  pvcDeletion: true
              pulsar:
                inCluster:
                  deletionPolicy: Delete
                  pvcDeletion: true
              storage:
                inCluster:
                  deletionPolicy: Delete
                  pvcDeletion: true
            components:
              image: {{workflow.parameters.milvus-image-repo}}:{{workflow.parameters.milvus-image-tag}}
              imagePullPolicy: Always
              queryNode:
                replicas: {{inputs.parameters.querynode-replicas}}
                resources:
                  requests:
                    memory: 500Mi
                  limits:
                    memory: {{inputs.parameters.datanode-memory-limit}}
              dataNode:
                replicas: {{inputs.parameters.datanode-replicas}}
                resources:
                  requests:
                    memory: 500Mi
                  limits:
                    memory: {{inputs.parameters.indexnode-memory-limit}}
              indexNode:
                replicas: {{inputs.parameters.indexnode-replicas}}
                resources:
                  requests:
                    memory: 500Mi
                  limits:
                    memory: {{inputs.parameters.indexnode-memory-limit}}
            config:
              log:
                level: debug
  arguments:
    parameters:
      - name: milvus-image-repo
        value: milvusdb/milvus-dev
      - name: milvus-image-tag
        value: 2.1.0-latest
      - name: milvus-release
        value: cluster-memory
  serviceAccountName: cluster-chaos-milvus
