apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: deploy-memory-milvus-standalone
  namespace: chaos-testing
spec:
  entrypoint: deploy-memory-milvus-standalone
  templates:
    - name: deploy-memory-milvus-standalone
      steps:
        - - name: deploy-milvus
            template: deploy-milvus
        - - name: wait-healthy
            templateRef:
              name: wait-milvus-healthy
              template: wait-milvus-healthy
              clusterScope: true
            arguments:
              parameters:
                - name: milvus-release
                  value: '{{workflow.parameters.milvus-release}}'
    - name: deploy-milvus
      inputs:
        parameters:
          - name: milvus-image-repo
            value: milvusdb/milvus-dev
          - name: milvus-image-tag
            value: 2.1.0-latest
          - name: standalone-replicas
            value: '1'
          - name: standalone-memory-limit
            value: 6Gi
      resource:
        action: apply
        manifest: |
          apiVersion: milvus.io/v1beta1
          kind: Milvus
          metadata:
            name: {{workflow.parameters.milvus-release}}
            namespace: default
            labels:
              app: milvus
          spec:
            mode: standalone
            dependencies:
              etcd:
                inCluster:
                  deletionPolicy: Delete
                  pvcDeletion: true
              storage:
                inCluster:
                  deletionPolicy: Delete
                  pvcDeletion: true
              rocksmq:
                persistence:
                  enabled: true
            components:
              image: {{inputs.parameters.milvus-image-repo}}:{{inputs.parameters.milvus-image-tag}}
              imagePullPolicy: Always
              resources:
                requests:
                  memory: 500Mi
                limits:
                  memory: {{inputs.parameters.standalone-memory-limit}}
            config:
              log:
                level: debug
  arguments:
    parameters:
      - name: milvus-release
        value: standalone-memory
  serviceAccountName: cluster-argo-milvus
