apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: standalone-memory-datanode
  namespace: qa
  labels:
    workflows.argoproj.io/test: standalone-datanode
spec:
  entrypoint: standalone-memory-datanode
  serviceAccountName: qa-admin
  arguments:
    parameters:
      - name: milvus-image-repo
        value: harbor.milvus.io/dockerhub/milvusdb/milvus-dev
      - name: milvus-image-tag
        value: 2.1.0-latest
      - name: milvus-release
        value: standalone-memory
      - name: collection-name
        value: standalone_data
  templates:
    - name: standalone-memory-datanode
      inputs:
        parameters:
          - name: standalone-memory-limit
            value: 6Gi
          - name: chaos-memory-size
            value: 6Gi
      dag:
        tasks:
          - name: deploy-standalone
            templateRef:
              name: deploy-memory-milvus-standalone
              template: deploy-memory-milvus-standalone
            arguments:
              parameters:
                - name: standalone-memory-limit
                  value: '{{inputs.parameters.standalone-memory-limit}}'
          - name: init-collection
            dependencies:
              - deploy-standalone
            templateRef:
              name: chaos-milvus-test
              template: milvus-test
            arguments:
              parameters:
                - name: milvus-case
                  value: test_init_collection
          - name: do-insert
            dependencies:
              - init-collection
            templateRef:
              name: chaos-milvus-test
              template: milvus-test
            arguments:
              parameters:
                - name: milvus-case
                  value: test_insert
          - name: apply-memory-chaos
            dependencies:
              - init-collection
            templateRef:
              name: chaos-memory-stress-by-label
              template: chaos-memory-stress-by-label
            arguments:
              parameters:
                - name: memory-size
                  value: '{{inputs.parameters.chaos-memory-size}}'
          - name: wait-pods-ready
            dependencies:
              - do-insert
              - apply-memory-chaos
            templateRef:
              name: wait-milvus-healthy
              template: wait-milvus-pods-ready
            arguments:
              parameters:
                - name: milvus-release
                  value: '{{workflow.parameters.milvus-release}}'
          - name: init-collection-check
            dependencies:
              - wait-pods-ready
            templateRef:
              name: chaos-milvus-test
              template: milvus-test
            arguments:
              parameters:
                - name: milvus-case
                  value: test_init_collection_check
          - name: e2e-test-check
            dependencies:
              - wait-pods-ready
            templateRef:
              name: e2e-test-check
              template: e2e-test-check
            arguments:
              parameters:
                - name: milvus-release
                  value: '{{workflow.parameters.milvus-release}}'
                - name: milvus-repo
                  value: 'https://github.com/ThreadDao/milvus.git'
                - name: milvus-branch
                  value: master-chaos-argo