apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: memory-standalone-datanode
  namespace: chaos-testing
spec:
  arguments:
    parameters:
      - name: milvus-release
        value: standalone-memory
      - name: collection-name
        value: test_memory
  templates:
    - name: memory-standalone-datanode-test
      dag:
        tasks:
          - name: deploy-milvus
            templateRef:
              name: deploy-memory-milvus-standalone
              template: deploy-memory-milvus-standalone
            arguments:
              parameters:
                - name: milvus-image-tag
                  value: 2.1.0-20220711-85117efd
          - name: init-collection
          - name: chaos-memory
            templateRef:
              name: chaos-memory-stress-by-label
              template: chaos-memory-stress-by-label
            arguments:
              parameters:
                - name: milvus-release
                  valus: '{{workflow.parameters.milvus-release}}'
                - name: chaos-component
                  value: standalone
                - name: memory-size
                  value: 6Gi
    - name: milvus-case
      inputs:
        parameters:
          - name: collection-name
          - name: test-case
      container:
        image: 'registry.milvus.io/milvus/milvus-test-env:v0.5'
        command:
          - /bin/sh
          - '-c'
        args:
          - >-
            cd /src/milvus/tests/python_client && pip install --upgrade
            setuptools && pip install --upgrade pip &&  pip install
            --no-cache-dir -r requirements.txt && pytest
            test_chaos_memory_argo.py::TestMilvusChaos::{{inputs.parameters.test-case}} --host={{inputs.parameters.milvus-release}}-milvus.default.svc.cluster.local --collection_name={{inputs.parameters.collection-name}} -v -s