apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: deploy-compact-milvus
  namespace: argo
spec:
  templates:
    - name: deploy-compact-milvus
      steps:
        - - name: deploy-compact-milvus
            template: deploy-milvus
        - - name: wait-healthy
            template: wait-healthy
    - name: deploy-milvus
      resource:
        action: apply
        manifest: |
          apiVersion: milvus.io/v1alpha1
          kind: Milvus
          metadata:
            name: '{{workflow.parameters.milvus-standalone-release}}'
            namespace: default
            labels:
              app: milvus
          spec:
            dependencies: 
              etcd:
                inCluster:
                  deletionPolicy: Delete
                  pvcDeletion: true
              storage:
                inCluster:
                  deletionPolicy: Delete
                  pvcDeletion: true
            image: harbor.zilliz.cc/milvus/milvus:{{workflow.parameters.milvus-image-tag}}
            config:
              log:
                level: debug
              common:
                retentionDuration: 40
    - name: wait-healthy
      script:
        image: bitnami/kubectl:1.21.4
        command: [ sh ]
        source: |
          kubectl -n default wait --for=condition=MilvusReady milvus/{{workflow.parameters.milvus-standalone-release}} --timeout 20m
          kubectl describe milvus {{workflow.parameters.milvus-standalone-release}}
  entrypoint: deploy-compact-milvus
  arguments:
    parameters:
      - name: milvus-image-tag
        value: master-latest
      - name: milvus-standalone-release
        value: milvus-compact
  serviceAccountName: cluster-argo-milvus