apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: deploy-compact-milvus
  namespace: argo
spec:
  serviceAccountName: cluster-argo-milvus
  arguments:
    parameters:
      - name: cluster-release
        value: my-cluster
      - name: standalone-release
        value: my-standalone
      - name: image-tag
        value: master-latest
  templates:
    - name: deploy-compact-cluster
      resource:
        action: apply
        manifest: |
          apiVersion: milvus.io/v1beta1
          kind: Milvus
          metadata:
            name: {{workflow.parameters.cluster-release}}
            namespace: default
            labels:
              app: milvus
          spec:
            mode: cluster
            dependencies: 
              etcd:
                inCluster:
                  deletionPolicy: Delete
                  pvcDeletion: true
              pulsar:
                inCluster:
                  deletionPolicy: Delete
                  pvcDeletion: true
              storage:
                inCluster:
                  deletionPolicy: Delete
                  pvcDeletion: true
            components:
              image: milvusdb/milvus-dev:{{workflow.parameters.image-tag}}
            config:
              log:
                level: debug
              common:
                retentionDuration: 40
    - name: deploy-compact-standalone
      resource:
        action: apply
        manifest: |
          apiVersion: milvus.io/v1beta1
          kind: Milvus
          metadata:
            name: {{workflow.parameters.standalone-release}}
            namespace: default
            labels:
              app: milvus
          spec:
            mode: standalone
            dependencies: 
              etcd:
                inCluster:
                  deletionPolicy: Delete
                  pvcDeletion: true
              storage:
                inCluster:
                  deletionPolicy: Delete
                  pvcDeletion: true
            components:
              image: milvusdb/milvus-dev:{{workflow.parameters.image-tag}}
            config:
              log:
                level: debug
              common:
                retentionDuration: 40