apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  annotations:
    workflows.argoproj.io/description: |
      Checkout out from Git and test application.
  name: chaos-test
spec:
  entrypoint: main
  volumeClaimTemplates:
    - metadata:
        name: workdir
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
  arguments:
    parameters:
      - name: repo
        value: https://github.com/milvus-io/milvus.git
      - name: branch
        value: master
      - name: host
        value: 10.100.32.156
      - name: port
        value: 30683
  templates:
    - name: main
      steps:
        - - name: run-test
            template: run-test
    # run test
    - name: run-test
      inputs:
        artifacts:
          - name: source
            path: /src/milvus
            git:
              repo: "{{workflow.parameters.repo}}"
              revision: "{{workflow.parameters.branch}}"
              insecureIgnoreHostKey: true
        parameters:
          - name: host
          - name: port
      container:
        image: milvusdb/pytest:20220525-de0ba6d
        command: [ sh, -c ]
        args: [ "
          cd /src/milvus/tests/python_client;
          pip install --upgrade pip;
          pip install --upgrade setuptools;
          pip install -r requirements.txt;
          pytest testcases/test_e2e.py --host {{workflow.parameters.host}} --port {{workflow.parameters.port}} -v -s
        " ]
