apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: walmart-test
  namespace: qa
spec:
  templates:
    - name: call-walmart-test
      inputs:
        parameters:
          - name: prepare-case
            value: '{{workflow.parameters.prepare-case}}'
          - name: parallel-insert-case
            value: '{{workflow.parameters.parallel-insert-case}}'
      outputs: {}
      metadata: {}
      steps:
        - - name: prepate-test
            template: walmart-test
            arguments:
              parameters:
                - name: case-name
                  value: '{{inputs.parameters.prepare-case}}'
        - - name: insert-test
            template: walmart-test
            arguments:
              parameters:
                - name: case-name
                  value: '{{inputs.parameters.parallel-insert-case}}'
            withSequence:
              count: '5'
    - name: walmart-test
      inputs:
        parameters:
          - name: case-name
        artifacts:
          - name: source
            path: /src/milvus
            git:
              repo: '{{workflow.parameters.milvus-repo}}'
              revision: '{{workflow.parameters.milvus-branch}}'
              insecureIgnoreHostKey: true
      outputs: {}
      metadata: {}
      container:
        name: test
        image: 'harbor.milvus.io/qa/fouram:1.1'
        command:
          - /bin/sh
          - '-c'
        args:
          - >-
            cd /src/milvus/tests/python_client && pip install --upgrade
            setuptools && pip install --upgrade pip &&  pip install
            --no-cache-dir -r requirements.txt && pytest
            testcases/test_walmart.py -k {{inputs.parameters.case-name}}
            --host={{workflow.parameters.milvus-release}}-milvus.chaos-testing.svc.cluster.local
            -v -s
        resources:
          limits:
            cpu: '5'
            memory: 3Gi
          requests:
            cpu: '2'
            memory: 1Gi
  entrypoint: call-walmart-test
  arguments:
    parameters:
      - name: milvus-release
        value: cluster-walmart
      - name: milvus-repo
        value: 'https://github.com/ThreadDao/milvus.git'
      - name: milvus-branch
        value: 2.2.0-walmart
      - name: prepare-case
        value: test_prepare
      - name: parallel-insert-case
        value: test_insert
  serviceAccountName: qa-admin
