apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: vdc-go-sdk-nightly
  namespace: qa
spec:
  workflowSpec:
    templates:
      - name: ref-vdc-go-sdk-ci
        steps:
          - - name: ref-vdc-go-sdk-ci
              templateRef:
                name: vdc-go-sdk-ci
                template: vdc-go-sdk-ci
      - name: uninstall-milvus
        inputs:
          parameters:
            - name: server-instance
          artifacts:
            - name: benchmark-src
              path: /src/benchmark
              git:
                repo: 'git@github.com:zilliztech/milvus_benchmark.git'
                revision: '{{workflow.parameters.test-client-branch}}'
                sshPrivateKeySecret:
                  name: github-key
                  key: ssh-private-key
                insecureIgnoreHostKey: true
        outputs: {}
        nodeSelector:
          node-role: test-client
        metadata: {}
        container:
          name: ''
          image: 'harbor-ap1.zilliz.cc/qa/fouram:1.1'
          command:
            - /bin/sh
            - '-c'
          args:
            - ' cd /src/benchmark &&  python3.8 -m pip install -i https://pypi.doubanio.com/simple/  --trusted-host pypi.doubanio.com --upgrade pip && python3.8 -m pip install -r requirements_3.8.txt -i https://pypi.doubanio.com/simple/ --trusted-host pypi.doubanio.com && cd /src/benchmark/milvus_benchmark/vdc/ && export PYTHONPATH=/src/benchmark && python3.8 -W ignore vdc_deploy.py --instance-name={{inputs.parameters.server-instance}} --deploy-mode=delete --env=UAT '
          resources: {}
          volumeMounts:
            - name: kube-config
              readOnly: true
              mountPath: /root/.kube
            - name: db-data-path
              mountPath: /test
        volumes:
          - name: db-data-path
            persistentVolumeClaim:
              claimName: qa-pvc
        tolerations:
          - key: node-role
            operator: Equal
            value: vdc-test
            effect: NoSchedule
      - name: uninstall-all
        steps:
          - - name: uninstall-milvus
              template: uninstall-milvus
              arguments:
                parameters:
                  - name: server-instance
                    value: '{{workflow.name}}-{{item.instanceId}}'
              withParam: '{{workflow.parameters.configmaps}}'
    entrypoint: ref-vdc-go-sdk-ci
    arguments:
      parameters:
        - name: activeDeadlineSeconds
          value: '1036800'
        - name: db-version-prefix
          value: nightly-
        - name: test-client-branch
          value: vdc
        - name: configmaps
          value: '[{"instanceId":"1", "server-configmap": "vdc-standalone-1cu"} ]'
    volumes:
      - name: kube-config
        secret:
          secretName: qa-admin-config
    onExit: uninstall-all
  schedule: 30 23 * * *
  timezone: Asia/Shanghai
