apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: vdc-go-sdk-ci
  namespace: qa
spec:
  templates:
    - name: vdc-go-sdk-ci
      inputs: {}
      outputs: {}
      metadata: {}
      steps:
        - - name: call-vdc-go-sdk-ci
            template: milvus-go-sdk-test
            arguments:
              parameters:
                - name: server-instance
                  value: '{{workflow.name}}-{{item.instanceId}}'
                - name: server-configmap
                  value: '{{item.server-configmap}}'
            withParam: '{{workflow.parameters.configmaps}}'
    - name: uninstall-all
      inputs: {}
      outputs: {}
      metadata: {}
      steps:
        - - name: uninstall-milvus
            template: uninstall-milvus
            arguments:
              parameters:
                - name: server-instance
                  value: '{{workflow.name}}-{{item.instanceId}}'
            withParam: '{{workflow.parameters.configmaps}}'
    - name: milvus-go-sdk-test
      inputs:
        parameters:
          - name: server-instance
          - name: server-configmap
      outputs: {}
      metadata: {}
      steps:
        - - name: install-milvus
            template: install-milvus
            arguments:
              parameters:
                - name: server-instance
                  value: '{{inputs.parameters.server-instance}}'
                - name: server-configmap
                  value: '{{inputs.parameters.server-configmap}}'
        - - name: go-ci-test
            template: go-ci-test
            arguments:
              artifacts:
                - name: endpoint
                  from: '{{steps.install-milvus.outputs.artifacts.endpoint}}'
    - name: install-milvus
      inputs:
        parameters:
          - name: server-instance
          - name: server-configmap
        artifacts:
          - name: benchmark-src
            path: /src/benchmark
            git:
              repo: 'git@github.com:zilliztech/milvus_benchmark.git'
              revision: '{{workflow.parameters.test-client-branch}}'
              sshPrivateKeySecret:
                name: github-key
                key: ssh-private-key
              insecureIgnoreHostKey: true
      outputs:
        artifacts:
          - name: endpoint
            path: /tmp/endpoint-pwd.txt
      nodeSelector:
        node-role: test-client
      metadata:
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: 'false'
      container:
        name: ''
        image: 'harbor-ap1.zilliz.cc/qa/fouram:1.1'
        command:
          - /bin/sh
          - '-c'
        args:
          - ' cd /src/benchmark &&  python3.8 -m pip install -i https://pypi.doubanio.com/simple/  --trusted-host pypi.doubanio.com --upgrade pip && python3.8 -m pip install -r requirements_3.8.txt -i https://pypi.doubanio.com/simple/ --trusted-host pypi.doubanio.com && cd /src/benchmark/milvus_benchmark/vdc/ && cp /configmap-server/config.yaml . && export PYTHONPATH=/src/benchmark && python3.8 -W ignore vdc_deploy.py --instance-name={{inputs.parameters.server-instance}} --db-version-prefix={{workflow.parameters.db-version-prefix}} --deploy-params=config.yaml --deploy-mode=install --env=UAT && python3.8 -W ignore vdc_deploy.py --instance-name={{inputs.parameters.server-instance}} --deploy-mode=get_endpoint_pwd  --env=UAT'
        resources: {}
        volumeMounts:
          - name: kube-config
            readOnly: true
            mountPath: /root/.kube
          - name: benchmark-server-configmap
            mountPath: /configmap-server
          - name: db-data-path
            mountPath: /test
      volumes:
        - name: benchmark-server-configmap
          configMap:
            name: '{{inputs.parameters.server-configmap}}'
        - name: db-data-path
          persistentVolumeClaim:
            claimName: qa-pvc
      tolerations:
        - key: node-role
          operator: Equal
          value: vdc-test
          effect: NoSchedule
    - name: go-ci-test
      inputs:
        artifacts:
          - name: endpoint
            path: /tmp/endpoint-pwd.txt
          - name: ci-source
            path: /src/milvus-cloud-test
            git:
              repo: 'git@github.com:ThreadDao/milvus-cloud-test.git'
              revision: go-test
              sshPrivateKeySecret:
                name: github-key
                key: ssh-private-key
              insecureIgnoreHostKey: true
      outputs: {}
      nodeSelector:
        node-role: test-client
      metadata:
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: 'false'
      container:
        name: ''
        image: 'golang:1.18.3-buster'
        command:
          - /bin/bash
          - '-c'
        args:
          - ' host=$(cat /tmp/endpoint-pwd.txt| awk ''NR == 1 {print $1}'') && echo $host && port=$(cat /tmp/endpoint-pwd.txt | awk ''NR == 2 {print $1}'') && echo $port && pwd=$(cat /tmp/endpoint-pwd.txt | awk ''NR == 3 {print $1}'') && cd /src/milvus-cloud-test/go_client && go get -u github.com/milvus-io/milvus-sdk-go/v2@master && curl -sSL "https://github.com/gotestyourself/gotestsum/releases/download/v1.8.2/gotestsum_1.8.2_linux_amd64.tar.gz" | tar -xz -C /usr/local/bin gotestsum && gotestsum --format testname --hide-summary=output ./testcases/... --addr=$host:$port --user=root --password=$pwd'
        resources:
          limits:
            cpu: '2'
            memory: 2Gi
          requests:
            cpu: '1'
            memory: 1Gi
      tolerations:
        - key: node-role
          operator: Equal
          value: vdc-test
          effect: NoSchedule
    - name: uninstall-milvus
      inputs:
        parameters:
          - name: server-instance
        artifacts:
          - name: benchmark-src
            path: /src/benchmark
            git:
              repo: 'git@github.com:zilliztech/milvus_benchmark.git'
              revision: '{{workflow.parameters.test-client-branch}}'
              sshPrivateKeySecret:
                name: github-key
                key: ssh-private-key
              insecureIgnoreHostKey: true
      outputs: {}
      nodeSelector:
        node-role: test-client
      metadata:
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: 'false'
      container:
        name: ''
        image: 'harbor-ap1.zilliz.cc/qa/fouram:1.1'
        command:
          - /bin/sh
          - '-c'
        args:
          - ' cd /src/benchmark &&  python3.8 -m pip install -i https://pypi.doubanio.com/simple/  --trusted-host pypi.doubanio.com --upgrade pip && python3.8 -m pip install -r requirements_3.8.txt -i https://pypi.doubanio.com/simple/ --trusted-host pypi.doubanio.com && cd /src/benchmark/milvus_benchmark/vdc/ && export PYTHONPATH=/src/benchmark && python3.8 -W ignore vdc_deploy.py --instance-name={{inputs.parameters.server-instance}} --deploy-mode=delete --env=UAT '
        resources: {}
        volumeMounts:
          - name: kube-config
            readOnly: true
            mountPath: /root/.kube
          - name: db-data-path
            mountPath: /test
      volumes:
        - name: db-data-path
          persistentVolumeClaim:
            claimName: qa-pvc
      tolerations:
        - key: node-role
          operator: Equal
          value: vdc-test
          effect: NoSchedule
  entrypoint: vdc-go-sdk-ci
  arguments:
    parameters:
      - name: activeDeadlineSeconds
        value: '1036800'
      - name: db-version-prefix
        value: nightly-
      - name: test-client-branch
        value: vdc
      - name: configmaps
        value: '[{"instanceId":"1", "server-configmap": "vdc-standalone-1cu"} ]'
  volumes:
    - name: kube-config
      secret:
        secretName: qa-admin-config
  onExit: uninstall-all