apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: compaction-test
spec:
  arguments:
    parameters:
      - name: milvus-release
        value: mic-test
      - name: milvus-image-tag
        value: master-20220619-516d9147
  entrypoint: compaction-test
  onExit: uninstall-mic
  templates:
    - name: compaction-test
      steps:
        - - name: deploy-mic
            templateRef:
              name: deploy-compact-mic
              template: deploy-compact-mic
            arguments:
              parameters:
                - name: milvus-image-tag
                  value: "{{workflow.parameters.milvus-image-tag}}"
                - name: milvus-release
                  value: "{{workflow.parameters.milvus-release}}"
        - - name: run-test
            template: run-test
    - name: run-test
      steps:
        - - name: check-healthy
            template: check-healthy
        - - name: client-test
            template: client-test
            when: "{{steps.check-healthy.outputs.result}} == Healthy"
        - - name: wait-healthy
            template: run-test
            when: "{{steps.check-healthy.outputs.result}} != Healthy"
    - name: check-healthy
      script:
        image: 'registry.milvus.io/milvus/milvus-test-env:v0.5'
        command: [sh]
        source: |
          sleep 300 && kubectl get mic {{workflow.parameters.milvus-release}} -o template --template={{.status.status}} -n default
    - name: client-test
      inputs:
        artifacts:
          - name: source
            path: /src/milvus
            git:
              repo: 'https://github.com/milvus-io/milvus.git'
              revision: 'master'
              insecureIgnoreHostKey: true
      container:
        image: 'registry.milvus.io/milvus/milvus-test-env:v0.5'
        command:
          - /bin/sh
          - '-c'
        args:
          - 'cd /src/milvus/tests/python_client && pip install --upgrade pip && pip install -r requirements.txt && pytest testcases/test_compaction.py -n 4 --host={{workflow.parameters.milvus-release}}-milvus.default.svc.cluster.local'
    - name: uninstall-mic
      container:
        name: main
        image: 'registry.milvus.io/milvus/milvus-test-env:v0.5'
        command:
          - /bin/sh
          - '-c'
        args:
          - 'kubectl delete mic {{workflow.parameters.milvus-release}} -n default'
  serviceAccountName: cluster-argo-milvus
  activeDeadlineSeconds: 3600
