# actually deploy mysql by helm
#  helm install argo-mysql bitnami/mysql \
#  --set image.repository=bitnami/mysql \
#  --set image.tag=5.7 \
#  --set auth.database=argo \
#  --set auth.username=mysql \
#  --set auth.password=xxxx \
#  --set primary.persistence.enabled=true \
#  --set fullnameOverride=argo-mysql -n argo
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
      name: mysql
    spec:
      containers:
        - env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: argo-mysql-config
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: argo-mysql-config
                  key: password
            - name: MYSQL_DATABASE
              value: argo
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: argo-mysql-config
                  key: rootpassword
          image: mysql:5.7
          name: main
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-persistent-storage
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim

